services:
  - type: web
    name: battletris-server
    env: node
    plan: free
    # Account: Github (digosfbf@gmail.com)
    # Deployment URL: https://battletris-server.onrender.com
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
