import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

const target = process.argv[2];
if (!target) {
    console.error('Error: Please specify the target environment (e.g. QA)');
    process.exit(1);
}

const targetLower = target.toLowerCase();
const yamlPath = path.join(process.cwd(), `config/${targetLower}.yaml`);
const envPath = path.join(process.cwd(), '.env');

if (!fs.existsSync(yamlPath)) {
    console.error(`Error: Configuration file ${yamlPath} not found.`);
    process.exit(1);
}

try {
    const fileContents = fs.readFileSync(yamlPath, 'utf8');
    const config = yaml.load(fileContents) as any;

    const envLines: string[] = [
        `# ==============================================================================`,
        `# DO NOT EDIT THIS FILE MANUALLY`,
        `# Generated from config/${targetLower}.yaml on ${new Date().toISOString()}`,
        `# ==============================================================================`,
        `NODE_ENV=${targetLower}`,
        ``
    ];

    // Explicit Mappings from YAML to standard ENVs

    // 1. URLs
    if (config['Frontend URL']) {
        envLines.push(`VITE_FRONTEND_URL=${config['Frontend URL']}`);
    }
    if (config['API URL']) {
        envLines.push(`VITE_API_URL=${config['API URL']}`);
        // Maintain backwards compatibility with the current project's Server URL name
        envLines.push(`SOCKET_SERVER_URL=${config['API URL']}`);
    }

    // 2. Database
    if (config['Database']) {
        if (config['Database']['host']) envLines.push(`DB_HOST=${config['Database']['host']}`);
        if (config['Database']['port']) envLines.push(`DB_PORT=${config['Database']['port']}`);
        if (config['Database']['db_name']) envLines.push(`DB_NAME=${config['Database']['db_name']}`);
    }

    // 3. Cache
    if (config['Cache']) {
        if (config['Cache']['host']) envLines.push(`REDIS_HOST=${config['Cache']['host']}`);
        if (config['Cache']['port']) envLines.push(`REDIS_PORT=${config['Cache']['port']}`);
    }

    // Default application port
    envLines.push(`PORT=8080`);

    fs.writeFileSync(envPath, envLines.join('\n'));
    console.log(`Successfully generated .env from config/${targetLower}.yaml`);
} catch (e) {
    console.error('Failed to parse YAML configuration.', e);
    process.exit(1);
}
