import fs from 'fs';
import path from 'path';

type SimpleYamlValue = string | number | boolean | SimpleYamlMap;
type SimpleYamlMap = { [key: string]: SimpleYamlValue };
const ENV_FLAG_NAME = "autocommiting";

const parseSimpleScalar = (raw: string): string | number | boolean => {
    const unquoted = raw.replace(/^['"]|['"]$/g, '').trim();
    if (/^(true|false)$/i.test(unquoted)) {
        return unquoted.toLowerCase() === 'true';
    }
    if (/^-?\d+(\.\d+)?$/.test(unquoted)) {
        return Number(unquoted);
    }
    return unquoted;
};

const parseSimpleYaml = (input: string): SimpleYamlMap => {
    const lines = input.split(/\r?\n/);
    let result: SimpleYamlMap = {};
    let currentParent: string | null = null;
    let currentIndent = 0;

    for (const rawLine of lines) {
        if (!rawLine.trim() || rawLine.trim().startsWith('#')) {
            continue;
        }

        const indentMatch = rawLine.match(/^(\s*)/);
        const indent = indentMatch ? indentMatch[1].length : 0;
        const line = rawLine.trim();
        const separatorIndex = line.indexOf(':');

        if (separatorIndex === -1) {
            throw new Error(`Invalid YAML line: "${rawLine}"`);
        }

        const key = line.slice(0, separatorIndex).trim();
        const valuePart = line.slice(separatorIndex + 1).trim();

        if (currentParent && indent <= currentIndent) {
            currentParent = null;
        }

        if (!valuePart) {
            currentParent = key;
            currentIndent = indent;
            if (result[key] === undefined) {
                result = { ...result, [key]: {} };
            }
            continue;
        }

        const value = parseSimpleScalar(valuePart);
        if (currentParent) {
            const existingParent = (result[currentParent] as SimpleYamlMap) || {};
            const updatedParent = { ...existingParent, [key]: value };
            result = { ...result, [currentParent]: updatedParent };
            continue;
        }

        result = { ...result, [key]: value };
    }

    return result;
};

const readEnvValue = (envFile: string, key: string): string => {
    if (!fs.existsSync(envFile)) {
        return "";
    }
    const lines = fs.readFileSync(envFile, "utf8").split(/\r?\n/);
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) {
            continue;
        }
        const entry = trimmed.startsWith("export ") ? trimmed.slice(7) : trimmed;
        if (!entry.includes("=")) {
            continue;
        }
        const [foundKey, ...rest] = entry.split("=");
        if (foundKey.trim() === key) {
            return rest.join("=").trim();
        }
    }
    return "";
};

const target = process.argv[2];
if (!target) {
    console.error('Error: Please specify the target environment (e.g. QA)');
    process.exit(1);
}

const targetLower = target.toLowerCase();
const yamlPath = path.join(process.cwd(), `config/${targetLower}-settings.yaml`);
const envPath = path.join(process.cwd(), '.env');

if (!fs.existsSync(yamlPath)) {
    console.error(`Error: Configuration file ${yamlPath} not found.`);
    process.exit(1);
}

try {
    const fileContents = fs.readFileSync(yamlPath, 'utf8');
    const config = parseSimpleYaml(fileContents);

    const infraRef = config['Infrastructure'];
    if (!infraRef || typeof infraRef !== 'string') {
        console.error(`Error: Infrastructure not set in config/${targetLower}-settings.yaml.`);
        process.exit(1);
    }

    const infraPath = path.isAbsolute(infraRef)
        ? infraRef
        : path.join(process.cwd(), infraRef);

    if (!fs.existsSync(infraPath)) {
        console.error(`Error: Infrastructure file ${infraPath} not found.`);
        process.exit(1);
    }

    const infraContents = fs.readFileSync(infraPath, 'utf8');
    const infra = parseSimpleYaml(infraContents);

    let envLines: string[] = [
        `# ==============================================================================`,
        `# DO NOT EDIT THIS FILE MANUALLY`,
        `# Generated from config/${targetLower}-settings.yaml on ${new Date().toISOString()}`,
        `# ==============================================================================`,
        `NODE_ENV=${targetLower}`,
        `INFRASTRUCTURE=${infraRef}`,
        ``
    ];

    // Explicit Mappings from YAML to standard ENVs

    // 1. URLs
    const infraFrontend = infra['Frontend URL'];
    const infraApi = infra['API URL'];
    const infraDeployment = infra['Deployment URL'];

    const frontendUrl = infraFrontend || infraDeployment;
    const apiUrl = infraApi || infraDeployment;

    if (!frontendUrl || !apiUrl) {
        console.error('Error: Infrastructure file must define Deployment URL or Frontend/API URL.');
        process.exit(1);
    }

    envLines = [...envLines, `VITE_FRONTEND_URL=${frontendUrl}`];
    envLines = [...envLines, `VITE_API_URL=${apiUrl}`];
    // Maintain backwards compatibility with the current project's Server URL name
    envLines = [...envLines, `SOCKET_SERVER_URL=${apiUrl}`];

    // 2. Database
    if (config['Database'] && typeof config['Database'] === 'object') {
        const database = config['Database'] as SimpleYamlMap;
        if (database['host']) envLines = [...envLines, `DB_HOST=${database['host']}`];
        if (database['port']) envLines = [...envLines, `DB_PORT=${database['port']}`];
        if (database['db_name']) envLines = [...envLines, `DB_NAME=${database['db_name']}`];
    }

    // 3. Cache
    if (config['Cache'] && typeof config['Cache'] === 'object') {
        const cache = config['Cache'] as SimpleYamlMap;
        if (cache['host']) envLines = [...envLines, `REDIS_HOST=${cache['host']}`];
        if (cache['port']) envLines = [...envLines, `REDIS_PORT=${cache['port']}`];
    }

    const existingAutocommitFlag = readEnvValue(envPath, ENV_FLAG_NAME);
    if (existingAutocommitFlag) {
        envLines = [...envLines, `${ENV_FLAG_NAME}=${existingAutocommitFlag}`];
    }

    // Default application port
    envLines = [...envLines, `PORT=8080`];

    fs.writeFileSync(envPath, envLines.join('\n'));
    console.log(`Successfully generated .env from config/${targetLower}-settings.yaml`);
} catch (e) {
    console.error('Failed to parse YAML configuration.', e);
    process.exit(1);
}
