#!/usr/bin/env bash

# ==============================================================================
# Universal Environment Switching Script
# Switches environment context between DEV, QA, UAT, and PROD.
# Usage: ./switch-env.sh [DEV|QA|UAT|PROD]
# ==============================================================================

TARGET=$(echo "$1" | tr '[:lower:]' '[:upper:]')
PROJECT_ROOT=$(pwd)
ARCHITECTURE_DOC="$PROJECT_ROOT/architecture_readme.md"

# Validation
if [[ ! "$TARGET" =~ ^(DEV|QA|UAT|PROD)$ ]]; then
    echo "Error: Target must be DEV, QA, UAT, or PROD."
    exit 1
fi

TARGET_LOWER=$(echo "$TARGET" | tr '[:upper:]' '[:lower:]')
YAML_FILE="$PROJECT_ROOT/config/${TARGET_LOWER}-settings.yaml"

if [ ! -f "$YAML_FILE" ]; then
    echo "Error: Configuration file $YAML_FILE not found."
    exit 1
fi

# ==============================================================================
# Generate .env from YAML (no external npm/tsx dependencies required)
# ==============================================================================
echo "Generating .env file from config/${TARGET_LOWER}-settings.yaml..."

python3 - "$TARGET" "$PROJECT_ROOT" <<'PYTHON'
import sys, os, datetime

target = sys.argv[1]
project_root = sys.argv[2]
target_lower = target.lower()
yaml_path = os.path.join(project_root, f"config/{target_lower}-settings.yaml")
env_path  = os.path.join(project_root, ".env")

def parse_yaml(path):
    """Simple YAML parser for key: value and one-level-deep sections."""
    result = {}
    current_section = None
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip()
            if not line or line.lstrip().startswith("#"):
                continue
            if raw[:1] in (" ", "\t"):          # indented → belongs to section
                if current_section is not None and ":" in line:
                    k, _, v = line.strip().partition(":")
                    result[current_section][k.strip()] = v.strip()
            else:                               # top-level key
                if ":" in line:
                    k, _, v = line.partition(":")
                    k, v = k.strip(), v.strip()
                    if v:
                        result[k] = v
                        current_section = None
                    else:
                        result[k] = {}
                        current_section = k
    return result

try:
    config = parse_yaml(yaml_path)
except Exception as e:
    print(f"Error: Failed to parse {yaml_path}: {e}", file=sys.stderr)
    sys.exit(1)

infra_ref = config.get("Infrastructure")
if not infra_ref:
    print(f"Error: Infrastructure not set in config/{target_lower}-settings.yaml.", file=sys.stderr)
    sys.exit(1)

infra_path = infra_ref if os.path.isabs(infra_ref) else os.path.join(project_root, infra_ref)
if not os.path.exists(infra_path):
    print(f"Error: Infrastructure file {infra_path} not found.", file=sys.stderr)
    sys.exit(1)

try:
    infra = parse_yaml(infra_path)
except Exception as e:
    print(f"Error: Failed to parse {infra_path}: {e}", file=sys.stderr)
    sys.exit(1)

frontend_url  = infra.get("Frontend URL")  or infra.get("Deployment URL")
api_url       = infra.get("API URL")       or infra.get("Deployment URL")

if not frontend_url or not api_url:
    print("Error: Infrastructure file must define Deployment URL or Frontend/API URL.", file=sys.stderr)
    sys.exit(1)

lines = [
    "# ==============================================================================",
    "# DO NOT EDIT THIS FILE MANUALLY",
    f"# Generated from config/{target_lower}-settings.yaml on {datetime.datetime.utcnow().isoformat()}",
    "# ==============================================================================",
    f"NODE_ENV={target_lower}",
    f"INFRASTRUCTURE={infra_ref}",
    "",
    f"VITE_FRONTEND_URL={frontend_url}",
    f"VITE_API_URL={api_url}",
    f"SOCKET_SERVER_URL={api_url}",
]

db = config.get("Database", {})
if db:
    if db.get("host"):    lines.append(f"DB_HOST={db['host']}")
    if db.get("port"):    lines.append(f"DB_PORT={db['port']}")
    if db.get("db_name"): lines.append(f"DB_NAME={db['db_name']}")

cache = config.get("Cache", {})
if cache:
    if cache.get("host"): lines.append(f"REDIS_HOST={cache['host']}")
    if cache.get("port"): lines.append(f"REDIS_PORT={cache['port']}")

lines.append("PORT=8080")

with open(env_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Successfully generated .env from config/{target_lower}-settings.yaml")
PYTHON

if [ $? -ne 0 ]; then
    echo "Error: Failed to generate .env file."
    exit 1
fi

echo "Switched to $TARGET environment (.env updated via YAML generation)."

# Update architecture_readme.md (if it exists)
if [ -f "$ARCHITECTURE_DOC" ]; then
    echo "Note: architecture_readme.md found. Agent will now update the environment table."
fi

echo "AGENT_SIGNAL: ENVIRONMENT_SWITCHED_TO_$TARGET"
